#!/bin/bash

DMENU="dmenu"
PLAYLISTS=""
ALL_MARK="[ALL]"

next_playlist_position() {
    echo $(($(mpc playlist | wc -l) + 1))
}

play_next_playlist() {
    local playing=$(mpc | grep -Eo "^\[playing\]")

    [ -z "$playing" ] && mpc play "$1" > /dev/null 2>&1
}

add_playlist() {
    local stations=$(mpc lsplaylists)

    local prefix=""
    local prompt="playlist"
    if [ -n "$1" ]; then
        prefix=$1"_"
        local prompt="playlist-$1"
        stations=$(echo "$stations" | grep "^$prefix" | sed "s/^$prefix//g")
    fi

    local playlists=$(echo "$stations" | sort | $DMENU -p "$prompt: ")
    if [ -n "$playlists" ]; then
        local number=$(next_playlist_position)
        while read -r playlist; do
            mpc load "${prefix}${playlist}" >/dev/null
        done <<< "$playlists"
        play_next_playlist "$number"
    fi
}

add_query() {
    local resources=$(mpc list "$1" | $DMENU -p "$1: ")
    if [ -n "$resources" ]; then
        local number=$(next_playlist_position)
        while read -r resource; do
            mpc findadd "$1" "$resource"
        done <<< "$resources"
        play_next_playlist "$number"
    fi
}

select_songs() {
    local artist="$1"
    local album="$2"
    local songs=$(echo -e "$ALL_MARK\n$(mpc list title album "$album")" | $DMENU -p "title: ")
    if [ "$songs" = "$ALL_MARK" ]; then
        mpc findadd album "$album"
    elif [ -n "$songs" ]; then
        while read -r song; do
            mpc findadd title "$song"
        done <<< "$songs"
    else
        select_album "$artist"
    fi
}

select_album() {
    local artist="$1"
    local album=$(echo -e "$ALL_MARK\n$(mpc list album artist "$artist")" | $DMENU -p "album: " | tail -n 1)
    if [ "$album" = "$ALL_MARK" ]; then
        mpc findadd artist "$artist"
    elif [ -n "$album" ]; then
        select_songs "$artist" "$album"
    else
        select_artist
    fi
}

select_artist() {
    [ -z "$all_artists" ] && all_artists=$(mpc list artist)
    local artist=$(echo -e "$ALL_MARK\n$all_artists" | $DMENU -p "artist: " | tail -n 1)
    if [ "$artist" = "$ALL_MARK" ]; then
        mpc listall | mpc add;
    elif [ -n "$artist" ]; then
        select_album "$artist"
    fi
}

add_library() {
    local number=$(next_playlist_position)

    select_artist

    play_next_playlist "$number"
}

get_playlist() {
    mpc -f "%position% - %artist% - %album% - %title%" playlist
}

start_playlist() {
    mpc play 1 > /dev/null 2>&1
}

goto_playlist() {
    local song=$(get_playlist | $DMENU -p "goto: " | tail -n 1)

    [ -n "$song" ] && mpc play "${song%%\ *}"
}

remove_playlist() {
    local songs=$(get_playlist | $DMENU -p "remove: " | sort -n -r)
    while read -r song; do
        mpc del "${song%%\ *}"
    done <<< "$songs"
}

shuffle_playlist() {
    mpc shuffle > /dev/null
}

save_playlist() {
    local playlist=$(mpc lsplaylists | sort | $DMENU -p "save: " | tail -n 1)
    [ -n "$playlist" ] && mpc save "$playlist"
}

delete_playlist() {
    local playlists=$(mpc lsplaylists | sort | $DMENU -p "save: ")
    while read -r playlist; do
        mpc rm "$playlist"
    done <<< "$playlists"
}

clear_playlist() {
    mpc clear > /dev/null
}

play_toggle() {
    mpc toggle > /dev/null
}

play_next() {
    mpc next > /dev/null
}

play_prev() {
    mpc prev > /dev/null
}

play_stop() {
    mpc stop > /dev/null
}

mpd_select() {
    status=$(mpc | head -n -1 | sed ':a;N;$!ba;s/\n/ /g' | sed s/#.*$// | xargs -I{} echo -e '\nstop\n(toggle) {}')
    selected=$(echo -e "${PLAYLISTS}artist\nalbum\ntitle\nlibrary\nstart playlist\ngoto in playlist\nremove from playlist\nshuffle playlist\nsave playlist\ndelete playlist\nclear playlist\nnext\nprevious$status" | $DMENU -p "mpd-select: " | tail -n 1)
    case $selected in
        playlist* )
            custom=$(echo "$selected" | awk -F- '{print $2}')
            add_playlist "$custom"
            ;;
        library )
            add_library
            ;;
        "start playlist" )
            start_playlist
            ;;
        "goto in playlist" )
            goto_playlist
            ;;
        "remove from playlist" )
            remove_playlist
            ;;
        "shuffle playlist" )
            shuffle_playlist
            ;;
        "delete playlist" )
            delete_playlist
            ;;
        "save playlist" )
            save_playlist
            ;;
        "clear playlist" )
            clear_playlist
            mpd_select
            ;;
        next )
            play_next
            ;;
        previous )
            play_prev
            ;;
        stop )
            play_stop
            ;;
        \(toggle\)* )
            play_toggle
            ;;
        * )
            [ "$selected" = "" ] || add_query "$selected"
            ;;
    esac
}

while getopts d:p: opt; do
  case $opt in
  d)
      DMENU=$OPTARG
      ;;
  p)
      PLAYLISTS="playlist-$OPTARG\n$PLAYLISTS"
      ;;
  esac
done

[ -z "$PLAYLISTS" ] && PLAYLISTS="playlist\n"

shift $((OPTIND - 1))

mpd_select
